# Generated by Django 3.0.4 on 2020-05-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='poems',
            new_name='poem',
        ),
    ]
